### ISSUE TITLE
No output in datamatrices

### ISSUE THREAD

**Issue by dwalke04** [adelabriere/SLAW#10]
Hello,
When running with our samples, I am receiving the following error in debug mode:
2021-11-10|22:12:05|DEBUG: stderr:Processing of 140 files.
Found 160 references peaks.
Found 0 peaks belonging to the model and 11300 new peaks
Found 139 files to process.
Starting batch.
Starting retention correction.
Computing density
Starting parallel processing 2021-11-10 22:09:51
End parallel processing 2021-11-10 22:10:57
Starting refinement 2021-11-10 22:10:57
Killed

As a result, no files are being output into the datamatrices folder. I've included the full debug session for reference. I did not have any issues running the example data. Is this a memory or processing issue?

Thanks!
[Debug_SLAW_10Nov.txt](https://github.com/adelabriere/SLAW/files/7516389/Debug_SLAW_10Nov.txt)

**Comment by dwalke04** [comment]
I'm including the full debug session output, it seems like there may have been some other errors contributing to this.

[Debug_SLAW_10Nov.txt](https://github.com/adelabriere/SLAW/files/7516373/Debug_SLAW_10Nov.txt)

**Comment by dwalke04** [comment]
I was able to correct this problem by increasing the amount of memory available to the docker. I made it through the next few steps and a feature table was output, but there seemed to be another error with the annotation step. Any help is appreciated.

Variables: 45001-48676 current cliques size is 15855
Annotating
Error in `[<-.data.frame`(`*tmp*`, pk.idx, , value = list(mz = c(NA_real_,  : 
  missing values are not allowed in subscripted assignments of data frames
Calls: groupFeatures ... standardGeneric -> eval -> eval -> eval -> mapply -> <Anonymous>
Environment:
  1: groupFeatures(dm, val_int_var, raw_files, opened_raw_files, match_files, ad
  2: annotateCliques(cliques, summarized_df, adducts, main_adducts, ionization_m
  3: mapply(cliques, as.list(seq_along(cliques)), FUN = annotateCliqueInterpretM
  4: standardGeneric("mapply")
  5: eval(mc, env)
  6: eval(mc, env)
  7: eval(mc, env)
  8: mapply(FUN = FUN, ..., MoreArgs = MoreArgs, SIMPLIFY = SIMPLIFY)
  9: (function (clique, adducts, main_adducts, ionization_mode, dm, val_int, ppm
  10: suppressWarnings(findMAIN(current_val[sel_idx, , drop = FALSE], ionmode = i
  11: withCallingHandlers(expr, warning = function(w) if (inherits(w, classes)) t
  12: findMAIN(current_val[sel_idx, , drop = FALSE], ionmode = ionization_mode, r
  13: lapply(1:length(matchingRules), function(i) formatResults(s, matchingRules[
  14: FUN(X[[i]], ...)
  15: formatResults(s, matchingRules[[i]], rules, prectab[i, ][, 1], prectab[i, ]
  16: `[<-`(`*tmp*`, pk.idx, , value = list(c(NA, NA, NA, NA, NA, NA, NA, NA, NA,
  17: `[<-.data.frame`(`*tmp*`, pk.idx, , value = list(c(NA, NA, NA, NA, NA, NA, 
  18: stop("missing values are not allowed in subscripted assignments of data fra
2021-11-11|00:30:26|INFO: Annotation finished
2021-11-11|00:30:26|INFO: STEP: annotation TOTAL_TIME:2599.32s LAST_STEP:475.30s
2021-11-11|00:30:26|INFO: Processing finished.

**Comment by adelabriere** [comment]
Hi, @dwalke04, could you please copy your parameters.txt and write me the polarity of your samples. Did you add some adducts ? It seems like an incorrect adduct could be the reason, if that is the case. Copying the full output would also be nice. Also, issues should now be opened in https://github.com/zamboni-lab/SLAW/issues.

Thanks

**Comment by dwalke04** [comment]
Hi @adelabriere,
Thank you for the response and all your help. I tried optimizing some of the parameters, and this seemed to correct the issue. This may have also been due to memory constraints. I'm still having some issues running the code, but will follow up with a new post on the other Github. Thanks!
