### ISSUE TITLE
Empty tables

### ISSUE THREAD

**Issue by bmgarcia** [adelabriere/SLAW#11]
Hello, 

I am attempting to use SLAW for the first time. I've been able to run this with the test data provided on Github perfectly and am very excited about the possibility of using this with my own data. 

For some reason when I've attempted to use the script with my own .mzML files the sbatch script runs fine with no errors, however the output folders are all empty. The individual datatable .csv files are all present however there is no data within any of those files, and the aligned data table folder is completely empty. 

Any assistance with why this works on the test data and i'm getting no errors/results with our own .mzml files would be extremely helpful.

Thanks,
Brianna M. Garcia

**Comment by adelabriere** [comment]
Hi @bmgarcia 

Are your mzML containing both negative and positive data ?
Could you please paste the parameters file ?

There is two potential reasons for this:
1. The default parameters are very off, this is not a problem if the optimization is set to true (See [here:](https://github.com/adelabriere/SLAW/wiki/Parameters-optimization) )
2. Your files cannot be read by the selected peakpicker.

If turning on optimization does not solve the problem, please rerun your processing and add the following flag: -e LOGGING=DEBUG and copy the output here and I ll try to help you.

Best,
Alexis

**Comment by bmgarcia** [comment]
Hi Alexis, 

Thank you for the response. 

So I determined our files were not centroided which was potentially causing some of the issue. 

I've now gone ahead and run the centroided data with the default openMS peak picking settings and it worked. 

We however are interested in using the ADAP peak picking algorithm, and when I switch over the parameter file to ADAP I end up with the same empty file situation. 

I've attached the output here.
[debugger_output.txt](https://github.com/adelabriere/SLAW/files/7823942/debugger_output.txt)

This was run with the default ADAP settings, if nothing looks weird in the debugger output I can try running the optimization. I tried last night (albeit with profile mode data and it crashed after 12 hours, but perhaps with the appropriate centroid it will work faster)

**Comment by bmgarcia** [comment]
To update: I have run the ADAP optimization and it looks like that combined with properly centroiding the data files has resolved the empty output problem. 

If you see any issues in the Debugger output that would be useful for me, please let me know. I greatly appreciate your help with overcoming these issues, and am very excited to move forward with pushing through our large dataset using your platform.

**Comment by adelabriere** [comment]
Hi @bmgarcia  I don t see a particular problem outside of the centroidization problem.

You should be fine. If your big dataset is problematic please first try with openMS or centwave as they are the fastest and easiest to optimize peakpicking.

If you encounter more issue please open an issue in the up-to-date [https://github.com/zamboni-lab/SLAW/issues](repos)
