### ISSUE TITLE
Empty Annotation files when using ADAP

### ISSUE THREAD

**Issue by bmgarcia** [adelabriere/SLAW#12]
Hello, 

When using the ADAP peak picking algorithm everything works fine however only 1 of the 3 outputs in the data matrices has data within them. All 3 .csv files are found within the folder, but only the datamatrices (non-annotated) has any results.

**Comment by adelabriere** [comment]
Hi @bmgarcia, this is an unknown bug. Could you send me the datamatrix to see if it is normally filled ? Could you also show me the log obitaned using -e LOGGING=DEBUG ?

Also could you please open your future issues in [the zamboni-lab repos](https://github.com/zamboni-lab/SLAW/issues)

**Comment by bmgarcia** [comment]
My apologies for putting this in the wrong repository. 

I've attached here the terminal output and the 1 data matrix. I don't get this issue when running ADAP with the test data provided, however when I use my own data this is a reoccurring issue. 

Thank you for your quick response. 

[datamatrix_6263d6e63679530f93ce08100e07f082.csv](https://github.com/adelabriere/SLAW/files/7842043/datamatrix_6263d6e63679530f93ce08100e07f082.csv)

[terminal_output.txt](https://github.com/adelabriere/SLAW/files/7842045/terminal_output.txt)

**Comment by adelabriere** [comment]
Dear @bmgarcia the bug is on my side and I ll fix it tomorrow. I always use area and it is actually hard-coded in the adduct annotation step.

You should be able to get your results using area, but I ll fix the problem tomorrow and tag you here when it is done.

**Comment by bmgarcia** [comment]
Thank you, I look forward to hearing back and appreciate the help with the issue.

**Comment by adelabriere** [comment]
Hi @bmgarcia  it should be fixed on both adelabriere/slaw:dev and adelabriere/slaw:latest thanks for catching this bug. Please please confirm me here that the processing finished so that I can close this issue :)

**Comment by bmgarcia** [comment]
Hi Alexis, 

I've tried re-processing our dataset with the adelabriere/slaw:latest and the three data matrices all appear to be working properly! Thank you for the help!
