### ISSUE TITLE
[wiki] Quick hands on

### ISSUE THREAD

**Issue by Adafede** [adelabriere/SLAW#2]
Hi,

Very nice and impressive repo! Will be useful to a lot of people!

Going through the [quick hands on](https://github.com/adelabriere/SLAW/wiki/Quick-hands-on:), encountered a really tiny details (as it is a wiki cannot create a pull request):

> Pick your demo data: Some demo data are provided here (**https://github.com/adelabriere/SLAW/tree/master/test/mzML**). If you want to pick your own data, go to step 3. If not you can jump to step 4.

Looks to be "https://github.com/adelabriere/SLAW/tree/master/test_data/" instead.

Congrats again!

**Comment by adelabriere** [comment]
100% right and corrected. Thanks !

Alexis
