### ISSUE TITLE
[feature request] Ability to work with gzipped mzML files

### ISSUE THREAD

**Issue by Adafede** [adelabriere/SLAW#4]
As for other tools, allowing to work with .mzML.gz files would be great! 👍🏼

**Comment by adelabriere** [comment]
I ll have a look at it but I don t think that they are supported by all the  peakpicker used (Centwave, FeatureFinderMetabo, ADAP). I ll check it

**Comment by Adafede** [comment]
Closing it here since the repo moved, if a repost on the other repo is needed happy to do! :)
